version: 0.1

phases:

  install:
    commands:
      - "npm install"

  pre_build:
    commands:
      - "npm test"

  build:
    commands:
      - "npm prune --production"

  post_build:
    commands:
      - "cat .manifest | xargs tar czf bundle.tgz"

artifacts:
  files:
    - bundle.tgz
    - .manifest
