# Here be a service
---
name: RPC.ApprovalService
version: 1.0.0
description: Manage the approval process for jobs.

main: src/index.js

configurations:
  - name: service
    key: /config/services/ApprovalService
    # approvalTableName

  - name: shared
    key: /config/shared
    # region
    # cacheEndpoint
    # logLevel
